### ISSUE TITLE
Support prevention of payload computations to be compiled out

### ISSUE THREAD

**Issue by alexeyr** [ivafanas/sltbench#68]
What nonius does:

> Sometimes the optimizer will optimize away the very code that you want to measure. There are several ways to use results that will prevent the optimiser from removing them. You can use the volatile keyword, or you can output the value to standard output or to a file, both of which force the program to actually generate the value somehow.

> Nonius adds a third option. **The values returned by any function provided as user code are guaranteed to be evaluated and not optimised out.** This means that if your user code consists of computing a certain value, you don't need to bother with using volatile or forcing output. Just return it from the function. That helps with keeping the code in a natural fashion.

In Google Benchmark we have slightly less convenient `DoNotOptimize` instead of returning the value.

It would be nice to have one of these approaches supported in sltbench too (if it's already there, I couldn't find it).

**Comment by alexeyr** [comment]
Or at least add to examples how to prevent optimization.

**Comment by ivafanas** [comment]
Well, it is just the first item of advanced guide:
https://github.com/ivafanas/sltbench/blob/master/doc/advanced_user_guide.md#preventing-benchmark-code-being-optimized-away

Let me note that return value optimization prevention might be not a something you want to. If input data is known at compile time, compiler might optimize intermediate computations due to inlining and constant propagation.

**Comment by alexeyr** [comment]
No idea how I overlooked it, sorry.
